### ISSUE TITLE
Wrong paths of added css / js files when website is in subfolder of web root

### ISSUE THREAD

**Issue by mockmeup** [bihor/fp_fractionslider#1]
### Setup

I have the latest version (1.1.1) installed and am doing a Typo3 update of a website locally (from v8 to v10). I'm running Mamp and accessing the website locally:

- http://localhost:8080/ points to a folder "workspace", 
- the website files are then located in (for example) "workspace/project-example-name-1/example-domain-1.de/www/..."
- URL in Browser is: http://localhost:8080/project-example-name-1/example-domain-1.de/www/

### Problem

a) JS/CSS files are included that way:

```
<re:addPublicResources path="fileadmin/_templates/vendors/slider-pro/1.4.0/css/slider-pro.min.css"></re:addPublicResources>
<re:addPublicResources path="fileadmin/_templates/vendors/slider-pro/1.4.0/js/jquery.sliderPro.min.js" compress="FALSE" footer="TRUE"></re:addPublicResources>
```

b) the AddPublicResourcesViewHelper-ViewHelper adds a leading "/" to the paths/urls, with the effect of "absolute" paths out of it:

```
// KGB: am Anfang wird immer ein / benötigt!
if (substr($path,0,1) != '/') {
  $path = '/' . $path;
}
```

c) This results to the following html-output:

```
<link rel="stylesheet" type="text/css" href="/fileadmin/_templates/vendors/slider-pro/1.4.0/css/slider-pro.min.css?1548428285" media="all">
```

d) which results in a 404-error, because 

`http://localhost:8080/fileadmin/_templates/vendors/slider-pro/1.4.0/css/slider-pro.min.css?1548428285`

doesn't exist.

This would be the correct URL:

`http://localhost:8080/project-example-name-1/example-domain-1.de/www/fileadmin/_templates/vendors/slider-pro/1.4.0/css/slider-pro.min.css?1548428285`

### Question / suggestion

I don't know why you - like the comment "KGB: am Anfang wird immer ein / benötigt!" states - need to add the leading slash before passing it to the pageRenderer. Please note that the "original" viewHelper from the news-Extension does not do it!

If you need that slash only because you want to check for the file's existence ( `if ($path === '' || !file_exists($basis . '/' . $path)) { ... `) then maybe it's better to add the slash just there?

However, currently the plugin - because of the implementation of that leading "slash" - appears to not be working when the website is residing in a subfolder of the web root.

### My "patch"

just fyi, I currently did the following:

```
// KGB: am Anfang wird immer ein / benötigt!
$slash = (substr($path, 0, 1) != '/') ? '/' : '';
if ($path === '' || !file_exists($basis . $slash . $path)) {
    //echo " not found: $basis$path ";
    return;
}
```

**Comment by bihor** [comment]
OK, I will repair it.

**Comment by bihor** [comment]
I have activated the argument addSlash. You now can set it to false.
Patch implemented too.
In version 1.1.2

**Comment by bihor** [comment]
I have replaced this Viewhelper in version 1.2.2 with the viewhelper from the TYPO3 core.
