### ISSUE TITLE
TypoScript object path "tt_content.list.20.fpfractionslider_pi1"  does not exist, in file /

### ISSUE THREAD

**Issue by adly123** [bihor/fp_fractionslider#2]
Exception: TypoScript object path "tt_content.list.20.fpfractionslider_pi1" does not exist, in file

**Comment by bihor** [comment]
![fraction2](https://user-images.githubusercontent.com/8191408/220307794-163fba08-edda-48bd-a0e8-a558c0ac7564.png)

Well, I can´t confirm this bug. Which TYPO3 verson did you used?
Composer mode or not?
